version: '3.1'

services:
  mysql8:
    image: mysql:8.0.34
    ports:
      - 3306:3306
    command: --default-authentication-plugin=caching_sha2_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
    volumes:
      - ./sales.sql:/docker-entrypoint-initdb.d/sales.sql
